import random
from datetime import datetime, timedelta


def random_date(start_d, end_d):
    delta = end_d - start_d
    random_days = random.randrange(delta.days)
    return start_d + timedelta(days=random_days)


start_date = datetime(2016, 1, 1)
end_date = datetime(2022, 12, 31)
dates = [random_date(start_date, end_date).strftime('%Y-%m-%d') for _ in range(100)]

book_names = [
    "The Great Gatsby",
    "To Kill a Mockingbird",
    "1984",
    "Pride and Prejudice",
    "The Catcher in the Rye",
    "Animal Farm",
    "Gone with the Wind",
    "Lord of the Flies",
    "The Hobbit",
    "Moby-Dick",
    "Brave New World",
    "The Grapes of Wrath",
    "Fahrenheit 451",
    "The Lord of the Rings",
    "The Adventures of Huckleberry Finn",
    "The Chronicles of Narnia",
    "One Hundred Years of Solitude",
    "The Kite Runner",
    "The Alchemist",
    "The Da Vinci Code",
    "Harry Potter and the Philosopher's Stone",
    "The Hunger Games",
    "The Hitchhiker's Guide to the Galaxy",
    "The Road",
    "The Picture of Dorian Gray",
    "Dracula",
    "Frankenstein",
    "Wuthering Heights",
    "Jane Eyre",
    "Great Expectations",
    "Alice's Adventures in Wonderland",
    "The Little Prince",
    "The Secret Garden",
    "Charlotte's Web",
    "Anne of Green Gables",
    "The Adventures of Tom Sawyer",
    "Treasure Island",
    "The Jungle Book",
    "Peter Pan",
    "The Wind in the Willows",
    "The Wonderful Wizard of Oz",
    "Little Women",
    "A Tale of Two Cities",
    "Les Misérables",
    "Crime and Punishment",
    "War and Peace",
    "The Brothers Karamazov",
    "Anna Karenina",
    "The Count of Monte Cristo",
    "Don Quixote",
    "Robinson Crusoe",
    "The Three Musketeers",
    "Gulliver's Travels",
    "The Swiss Family Robinson",
    "Around the World in Eighty Days",
    "Journey to the Center of the Earth",
    "Twenty Thousand Leagues Under the Sea",
    "The Time Machine",
    "The War of the Worlds",
    "The Invisible Man",
    "The Island of Doctor Moreau",
    "The Call of the Wild",
    "White Fang",
    "Tarzan of the Apes",
    "King Solomon's Mines",
    "She",
    "Heart of Darkness",
    "The Strange Case of Dr. Jekyll and Mr. Hyde",
    "The Adventures of Sherlock Holmes",
    "The Hound of the Baskervilles",
    "The Sign of the Four",
    "The Valley of Fear",
    "A Study in Scarlet",
    "The Memoirs of Sherlock Holmes",
    "The Return of Sherlock Holmes",
    "His Last Bow",
    "The Case-Book of Sherlock Holmes",
    "Jurassic Park",
    "The Andromeda Strain",
    "Sphere",
    "Congo",
    "Timeline",
    "Prey",
    "Next",
    "State of Fear",
    "The Lost World",
    "Micro",
    "Pirate Latitudes",
    "Dragon Teeth",
    "Rising Sun",
    "Airframe",
    "Disclosure",
    "Eaters of the Dead",
    "Terminal Man",
    "Travels",
    "Binary",
    "Twister",
    "The Great Train Robbery",
    "Congo",
    "Grave Descend",
    "Scratch One",
    "Zero Cool"
]

with open('books.txt', 'w') as file:
    for i in range(100):
        file.write(f"{dates[i]},{random.choice(book_names)}\n")
